name: Deploy to Amazon EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      CI: false

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Prepare SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add EC2 instance to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan 3.22.119.230 >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        scp -r ./src/* ubuntu@3.22.119.230:/home/ubuntu/abhi
